import { homedir } from 'node:os'
import { basename, dirname, extname, join, normalize, relative, resolve, sep } from 'node:path'
import { existsSync } from 'node:fs'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'

const ROUTE = '/plugin/dsh-learning-coder'
const CONFIG_PATH = join(homedir(), '.config', 'dsh-learning-coder', 'config.json')
const DEFAULT_LIBRARY = join(homedir(), 'Documents', 'Obsidian', 'Development')
const MAX_CHAPTERS = 200

export const name = 'dsh-learning-coder'
export const inject = ['webServer', 'sessionQuery']

let config = {
  libraryRoot: DEFAULT_LIBRARY,
  vaultMode: 'absolute-path',
}

async function loadConfig() {
  try {
    const raw = await readFile(CONFIG_PATH, 'utf8')
    const parsed = JSON.parse(raw)
    if (typeof parsed.libraryRoot === 'string' && parsed.libraryRoot.trim()) config.libraryRoot = resolveTilde(parsed.libraryRoot.trim())
    if (parsed.vaultMode === 'absolute-path' || parsed.vaultMode === 'folder') config.vaultMode = parsed.vaultMode
  } catch {
    // Defaults are intentionally usable on a fresh install.
  }
}

async function saveConfig(next) {
  config = { ...config, ...next }
  await mkdir(dirname(CONFIG_PATH), { recursive: true })
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf8')
}

function resolveTilde(value) {
  if (value === '~') return homedir()
  if (value.startsWith('~/') || value.startsWith('~\\')) return join(homedir(), value.slice(2))
  return value
}

function cleanProjectName(cwd) {
  const raw = basename(cwd.replace(/[\\/]+$/, '')) || 'workspace'
  return raw.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'workspace'
}

function workspaceKey(cwd) {
  return createHash('sha1').update(cwd).digest('hex').slice(0, 8)
}

function isInside(parent, candidate) {
  const p = resolve(parent)
  const c = resolve(candidate)
  const r = relative(p, c)
  return r === '' || (!r.startsWith('..' + sep) && r !== '..' && !r.startsWith('/'))
}

function workspaceDir(cwd) {
  return join(config.libraryRoot, cleanProjectName(cwd))
}

function safeChapterPath(cwd, relativePath) {
  const root = workspaceDir(cwd)
  const target = resolve(root, relativePath)
  if (!isInside(root, target)) throw new Error('Path is outside the workspace learning library')
  return target
}

async function ensureWorkspace(cwd) {
  const dir = workspaceDir(cwd)
  await mkdir(dir, { recursive: true })
  const indexPath = join(dir, 'index.md')
  if (!existsSync(indexPath)) {
    const project = cleanProjectName(cwd)
    const index = `---\ntype: learning-index\nproject: ${project}\nworkspace_path: ${cwd}\n---\n\n# ${project} Learning\n\n> Workspace-level learning library generated by DSH Learning Coder.\n\n## Recent chapters\n\n\\`\\`\\`dataview\nTABLE date, task_type, difficulty, topics\nFROM ""\nWHERE type = "learning"\nSORT date DESC\nLIMIT 20\n\\`\\`\\`\n\n## Technologies\n\n\\`\\`\\`dataview\nTABLE length(rows) AS "Chapters"\nFROM ""\nWHERE type = "learning"\nFLATTEN technologies AS technology\nGROUP BY technology\nSORT length(rows) DESC\n\\`\\`\\`\n\n## Concepts\n\n\\`\\`\\`dataview\nTABLE length(rows) AS "Chapters"\nFROM ""\nWHERE type = "learning"\nFLATTEN concepts AS concept\nGROUP BY concept\nSORT length(rows) DESC\n\\`\\`\\`\n\n## Workspace\n\`${cwd}\`\n`
    await writeFile(indexPath, index, 'utf8')
  }
  return dir
}

async function listMarkdown(dir, base = dir, out = []) {
  if (out.length >= MAX_CHAPTERS) return out
  let entries = []
  try { entries = await readdir(dir, { withFileTypes: true }) } catch { return out }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      await listMarkdown(full, base, out)
      if (out.length >= MAX_CHAPTERS) break
    } else if (extname(entry.name).toLowerCase() === '.md') {
      const rel = relative(base, full).split(sep).join('/')
      let title = entry.name.replace(/\.md$/i, '')
      let metadata = {}
      try {
        const raw = await readFile(full, 'utf8')
        const m = /^---\n([\s\S]*?)\n---\n/.exec(raw)
        if (m) {
          for (const line of m[1].split('\n')) {
            const match = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line.trim())
            if (match) metadata[match[1]] = match[2].replace(/^['"]|['"]$/g, '')
          }
          if (metadata.title) title = metadata.title
        }
      } catch {}
      out.push({ path: rel, title, type: metadata.type || 'note', date: metadata.date || null, taskType: metadata.task_type || null, difficulty: metadata.difficulty || null })
      if (out.length >= MAX_CHAPTERS) break
    }
  }
  return out
}

async function workspaceInfo(sessionId, sessionQuery) {
  if (!sessionId) throw new Error('sessionId is required')
  const snapshot = await sessionQuery.readSession(sessionId)
  const cwd = snapshot.session.cwd
  if (!cwd) throw new Error('Current session has no workspace cwd')
  const dir = await ensureWorkspace(cwd)
  const chapters = await listMarkdown(dir)
  chapters.sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')) || a.title.localeCompare(b.title))
  return {
    sessionId,
    workspace: {
      cwd,
      name: cleanProjectName(cwd),
      libraryPath: dir,
      chapterCount: chapters.filter(item => item.type === 'learning').length,
      chapters,
      workspaceKey: workspaceKey(cwd),
    },
    config: { ...config },
  }
}

function json(res, status, value) {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
    'X-Content-Type-Options': 'nosniff',
  })
  res.end(JSON.stringify(value))
}

function readJsonBody(req) {
  return new Promise(resolveBody => {
    let body = ''
    req.on('data', chunk => { if (body.length < 200_000) body += chunk })
    req.on('end', () => {
      if (!body.trim()) return resolveBody({})
      try { resolveBody(JSON.parse(body)) } catch { resolveBody({ parseError: true }) }
    })
    req.on('error', () => resolveBody({}))
  })
}

async function openExternal(target) {
  const { execFile } = await import('node:child_process')
  const { promisify } = await import('node:util')
  const exec = promisify(execFile)
  if (process.platform === 'darwin') return exec('open', [target])
  if (process.platform === 'win32') return exec('cmd', ['/c', 'start', '', target])
  return exec('xdg-open', [target])
}

async function handle(req, res, sub, sessionQuery, log) {
  if (sub === 'settings') {
    if (req.method === 'GET') return json(res, 200, { ...config, configPath: CONFIG_PATH })
    if (req.method !== 'POST') return json(res, 405, { error: 'Method Not Allowed' })
    const body = await readJsonBody(req)
    if (body.parseError || typeof body.libraryRoot !== 'string' || !body.libraryRoot.trim()) return json(res, 400, { error: 'libraryRoot is required' })
    const root = resolveTilde(body.libraryRoot.trim())
    await mkdir(root, { recursive: true })
    await saveConfig({ libraryRoot: root })
    return json(res, 200, { ok: true, ...config })
  }

  if (sub === 'workspace') {
    if (req.method !== 'GET') return json(res, 405, { error: 'Method Not Allowed' })
    try {
      const url = new URL(req.url || '/', 'http://localhost')
      return json(res, 200, await workspaceInfo(url.searchParams.get('sessionId'), sessionQuery))
    } catch (error) {
      return json(res, 400, { error: error instanceof Error ? error.message : String(error) })
    }
  }

  if (sub === 'open') {
    if (req.method !== 'POST') return json(res, 405, { error: 'Method Not Allowed' })
    const body = await readJsonBody(req)
    if (body.parseError || typeof body.sessionId !== 'string') return json(res, 400, { error: 'sessionId is required' })
    try {
      const info = await workspaceInfo(body.sessionId, sessionQuery)
      const root = info.workspace.libraryPath
      let target = root
      if (typeof body.path === 'string' && body.path.trim()) target = safeChapterPath(info.workspace.cwd, body.path.trim())
      if (body.mode === 'obsidian') {
        const uri = `obsidian://open?path=${encodeURIComponent(target)}`
        await openExternal(uri)
      } else {
        await openExternal(target)
      }
      return json(res, 200, { ok: true, target })
    } catch (error) {
      return json(res, 400, { error: error instanceof Error ? error.message : String(error) })
    }
  }

  if (sub === 'health') return json(res, 200, { ok: true, name })
  return json(res, 404, { error: 'Not found' })
}

export async function apply(ctx) {
  await loadConfig()
  const webServer = ctx.webServer
  if (!webServer || typeof webServer.register !== 'function') {
    ctx.logger?.warn?.('[dsh-learning-coder] webServer unavailable; routes disabled')
    return
  }
  const sessionQuery = ctx.sessionQuery
  webServer.register({
    kind: 'prefix',
    path: ROUTE,
    handler: async (req, res) => {
      const url = new URL(req.url || '/', 'http://localhost')
      const sub = url.pathname.replace(/^\/plugin\/dsh-learning-coder\/?/, '')
      await handle(req, res, sub, sessionQuery, message => ctx.logger?.info?.(message))
    },
  })
  ctx.logger?.info?.('[dsh-learning-coder] workspace learning routes registered')
}
