import { homedir } from 'node:os'
import { basename, dirname, extname, join, relative, resolve, sep } from 'node:path'
import { existsSync } from 'node:fs'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { createUserMessage } from '@deepseek-ai/dsh-llm'

const ROUTE = '/plugin/dsh-learning-coder'
const CONFIG_PATH = join(homedir(), '.config', 'dsh-learning-coder', 'config.json')
const DEFAULT_LIBRARY = join(homedir(), 'Documents', 'Obsidian', 'Development')
const MAX_CHAPTERS = 200
const AUTO_SOURCE = { kind: 'plugin', plugin: 'dsh-learning-coder', form: 'instructions' }
const AUTO_TRIGGER_PREFIX = '[DSH Learning Coder — automatic post-task documentation]'

export const name = 'dsh-learning-coder'
export const inject = ['webServer', 'sessionQuery']

let config = {
  libraryRoot: DEFAULT_LIBRARY,
  vaultMode: 'absolute-path',
}

async function loadConfig() {
  try {
    const raw = await readFile(CONFIG_PATH, 'utf8')
    const parsed = JSON.parse(raw)
    if (typeof parsed.libraryRoot === 'string' && parsed.libraryRoot.trim()) {
      config.libraryRoot = resolveTilde(parsed.libraryRoot.trim())
    }
    if (parsed.vaultMode === 'absolute-path' || parsed.vaultMode === 'folder') {
      config.vaultMode = parsed.vaultMode
    }
  } catch {
    // Defaults are intentionally usable on a fresh install.
  }
}

async function saveConfig(next) {
  config = { ...config, ...next }
  await mkdir(dirname(CONFIG_PATH), { recursive: true })
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf8')
}

function resolveTilde(value) {
  if (value === '~') return homedir()
  if (value.startsWith('~/') || value.startsWith('~\\')) return join(homedir(), value.slice(2))
  return value
}

function cleanProjectName(cwd) {
  const raw = basename(cwd.replace(/[\\/]+$/, '')) || 'workspace'
  return raw.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'workspace'
}

function workspaceDir(cwd) {
  return join(config.libraryRoot, cleanProjectName(cwd))
}

function isInside(parent, candidate) {
  const p = resolve(parent)
  const c = resolve(candidate)
  const r = relative(p, c)
  return r === '' || (!r.startsWith('..' + sep) && r !== '..' && !r.startsWith('/'))
}

function safeChapterPath(cwd, relativePath) {
  const root = workspaceDir(cwd)
  const target = resolve(root, relativePath)
  if (!isInside(root, target)) throw new Error('Path is outside the workspace learning library')
  return target
}

async function ensureWorkspace(cwd) {
  const dir = workspaceDir(cwd)
  await mkdir(dir, { recursive: true })
  const indexPath = join(dir, 'index.md')

  if (!existsSync(indexPath)) {
    const project = cleanProjectName(cwd)
    const index = [
      '---',
      'type: learning-index',
      'project: ' + project,
      'workspace_path: ' + cwd,
      '---',
      '',
      '# ' + project + ' Learning',
      '',
      '> Workspace-level learning library generated by DSH Learning Coder.',
      '',
      '## Recent chapters',
      '',
      '```dataview',
      'TABLE date, task_type, difficulty, topics',
      'FROM ""',
      'WHERE type = "learning"',
      'SORT date DESC',
      'LIMIT 20',
      '```',
      '',
      '## Technologies',
      '',
      '```dataview',
      'TABLE length(rows) AS "Chapters"',
      'FROM ""',
      'WHERE type = "learning"',
      'FLATTEN technologies AS technology',
      'GROUP BY technology',
      'SORT length(rows) DESC',
      '```',
      '',
      '## Concepts',
      '',
      '```dataview',
      'TABLE length(rows) AS "Chapters"',
      'FROM ""',
      'WHERE type = "learning"',
      'FLATTEN concepts AS concept',
      'GROUP BY concept',
      'SORT length(rows) DESC',
      '```',
      '',
      '## Workspace',
      '',
      '<code>' + cwd + '</code>',
      '',
    ].join('\n')
    await writeFile(indexPath, index, 'utf8')
  }

  return dir
}

async function listMarkdown(dir, base = dir, out = []) {
  if (out.length >= MAX_CHAPTERS) return out

  let entries = []
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return out
  }

  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue
    const full = join(dir, entry.name)

    if (entry.isDirectory()) {
      await listMarkdown(full, base, out)
      if (out.length >= MAX_CHAPTERS) break
      continue
    }

    if (extname(entry.name).toLowerCase() !== '.md') continue

    let title = entry.name.replace(/\.md$/i, '')
    let metadata = {}

    try {
      const raw = await readFile(full, 'utf8')
      const match = /^---\n([\s\S]*?)\n---\n/.exec(raw)
      if (match) {
        for (const line of match[1].split('\n')) {
          const item = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line.trim())
          if (item) metadata[item[1]] = item[2].replace(/^['"]|['"]$/g, '')
        }
        if (metadata.title) title = metadata.title
      }
    } catch {
      // A single unreadable note should not break the library view.
    }

    out.push({
      path: relative(base, full).split(sep).join('/'),
      title,
      type: metadata.type || 'note',
      date: metadata.date || null,
      taskType: metadata.task_type || null,
      difficulty: metadata.difficulty || null,
    })

    if (out.length >= MAX_CHAPTERS) break
  }

  return out
}

async function workspaceInfo(sessionId, sessionQuery) {
  if (!sessionId) throw new Error('sessionId is required')
  if (!sessionQuery || typeof sessionQuery.readSession !== 'function') {
    throw new Error('sessionQuery service is unavailable')
  }

  const snapshot = await sessionQuery.readSession(sessionId)
  const cwd = snapshot?.session?.cwd
  if (!cwd) throw new Error('Current session has no workspace cwd')

  const dir = await ensureWorkspace(cwd)
  const chapters = await listMarkdown(dir)
  chapters.sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')) || a.title.localeCompare(b.title))

  return {
    sessionId,
    workspace: {
      cwd,
      name: cleanProjectName(cwd),
      libraryPath: dir,
      chapterCount: chapters.filter(item => item.type === 'learning').length,
      chapters,
    },
    config: { ...config },
  }
}

function json(res, status, value) {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
    'X-Content-Type-Options': 'nosniff',
  })
  res.end(JSON.stringify(value))
}

function readJsonBody(req) {
  return new Promise(resolveBody => {
    let body = ''
    req.on('data', chunk => {
      if (body.length < 200_000) body += chunk
    })
    req.on('end', () => {
      if (!body.trim()) return resolveBody({})
      try {
        resolveBody(JSON.parse(body))
      } catch {
        resolveBody({ parseError: true })
      }
    })
    req.on('error', () => resolveBody({}))
  })
}

async function openExternal(target) {
  const { execFile } = await import('node:child_process')
  const { promisify } = await import('node:util')
  const exec = promisify(execFile)

  if (process.platform === 'darwin') return exec('open', [target])
  if (process.platform === 'win32') return exec('cmd', ['/c', 'start', '', target])
  return exec('xdg-open', [target])
}

function currentTurnHasWork(agent, turn) {
  return agent.session.events.some(event => event.type === 'tool/call' && event.data.turn === turn)
}

function currentTurnWasAutomaticDocumentation(agent, turn) {
  const turnStart = agent.session.events.findLast(event => event.type === 'turn/start' && event.data.turn === turn)
  if (!turnStart) return false

  return agent.session.events.some(event => {
    if (event.type !== 'user/message' || event.seq < turnStart.seq) return false
    const message = event.data
    return message.source?.kind === 'plugin'
      && message.source?.plugin === name
      && message.content?.some(block => block.type === 'text' && block.text.startsWith(AUTO_TRIGGER_PREFIX))
  })
}

async function installAutomaticSkill(ctx) {
  const skills = ctx.get?.('skills')
  if (!skills || typeof skills.register !== 'function') {
    ctx.logger?.warn?.('[dsh-learning-coder] skill registry unavailable; automatic skill registration skipped')
    return
  }

  try {
    const content = await readFile(new URL('../skills/learning-coder/SKILL.md', import.meta.url), 'utf8')
    skills.register({
      name: 'learning-coder',
      description: 'Automatically turn meaningful completed coding work into an accurate, visual, Obsidian-friendly learning chapter for the current workspace.',
      content,
      invocation: { modelInvocable: true, userInvocable: true },
    })
    ctx.logger?.info?.('[dsh-learning-coder] automatic learning skill registered')
  } catch (error) {
    ctx.logger?.warn?.(`[dsh-learning-coder] could not register learning skill: ${String(error)}`)
  }
}

function scheduleAutomaticDocumentation(ctx, agent, turn, signal) {
  if (signal.aborted) return
  if (!currentTurnHasWork(agent, turn)) return
  if (currentTurnWasAutomaticDocumentation(agent, turn)) return

  const cwd = agent.session.header.cwd
  if (!cwd) return

  const library = workspaceDir(cwd)
  const prompt = [
    AUTO_TRIGGER_PREFIX,
    'A meaningful coding turn has just completed. This is an automatic background documentation pass; the user does not need to ask for it.',
    '',
    `Workspace: ${cwd}`,
    `Learning library for this workspace: ${library}`,
    '',
    'Use the learning-coder skill and inspect the completed turn/session evidence before writing anything.',
    'If the completed work is trivial, purely conversational, exploratory without a completed change, or otherwise not educational, do not create a chapter.',
    'Otherwise create or update exactly one Obsidian Markdown learning chapter for the completed task inside the workspace library above.',
    'The chapter belongs to the workspace, not to this session. Do not create session logs.',
    'Do not ask the user for confirmation. Do not modify application source code. Only create/update the learning artifact and any necessary workspace learning index metadata.',
    'Make the chapter visually readable in Obsidian: use concise headings, focused code snippets, useful Mermaid/ASCII diagrams where they improve understanding, and Obsidian callouts without emoji.',
    'After writing the chapter, briefly report the chapter path and what it teaches.',
  ].join('\n')

  queueMicrotask(() => {
    if (signal.aborted) return
    try {
      agent.followup(createUserMessage({
        content: [{ type: 'text', text: prompt }],
        source: AUTO_SOURCE,
      }))
    } catch (error) {
      ctx.logger?.warn?.(`[dsh-learning-coder] automatic documentation could not be queued: ${String(error)}`)
    }
  })
}

async function handle(req, res, sub, sessionQuery) {
  if (sub === 'settings') {
    if (req.method === 'GET') return json(res, 200, { ...config, configPath: CONFIG_PATH })
    if (req.method !== 'POST') return json(res, 405, { error: 'Method Not Allowed' })

    const body = await readJsonBody(req)
    if (body.parseError || typeof body.libraryRoot !== 'string' || !body.libraryRoot.trim()) {
      return json(res, 400, { error: 'libraryRoot is required' })
    }

    const root = resolveTilde(body.libraryRoot.trim())
    await mkdir(root, { recursive: true })
    await saveConfig({ libraryRoot: root })
    return json(res, 200, { ok: true, ...config })
  }

  if (sub === 'workspace') {
    if (req.method !== 'GET') return json(res, 405, { error: 'Method Not Allowed' })

    try {
      const url = new URL(req.url || '/', 'http://localhost')
      return json(res, 200, await workspaceInfo(url.searchParams.get('sessionId'), sessionQuery))
    } catch (error) {
      return json(res, 400, { error: error instanceof Error ? error.message : String(error) })
    }
  }

  if (sub === 'open') {
    if (req.method !== 'POST') return json(res, 405, { error: 'Method Not Allowed' })

    const body = await readJsonBody(req)
    if (body.parseError || typeof body.sessionId !== 'string') {
      return json(res, 400, { error: 'sessionId is required' })
    }

    try {
      const info = await workspaceInfo(body.sessionId, sessionQuery)
      const root = info.workspace.libraryPath
      let target = root

      if (typeof body.path === 'string' && body.path.trim()) {
        target = safeChapterPath(info.workspace.cwd, body.path.trim())
      }

      if (body.mode === 'obsidian') {
        await openExternal('obsidian://open?path=' + encodeURIComponent(target))
      } else {
        await openExternal(target)
      }

      return json(res, 200, { ok: true, target })
    } catch (error) {
      return json(res, 400, { error: error instanceof Error ? error.message : String(error) })
    }
  }

  if (sub === 'health') return json(res, 200, { ok: true, name })
  return json(res, 404, { error: 'Not found' })
}

export async function apply(ctx) {
  await loadConfig()
  await installAutomaticSkill(ctx)

  const webServer = ctx.webServer
  if (!webServer || typeof webServer.register !== 'function') {
    ctx.logger?.warn?.('[dsh-learning-coder] webServer unavailable; routes disabled')
  } else {
    const sessionQuery = ctx.sessionQuery
    ctx.effect(
      () => webServer.register({
        kind: 'prefix',
        path: ROUTE,
        handler: async (req, res) => {
          const url = new URL(req.url || '/', 'http://localhost')
          const sub = url.pathname.replace(/^\/plugin\/dsh-learning-coder\/?/, '')
          await handle(req, res, sub, sessionQuery)
        },
      }),
      'dsh-learning-coder: workspace routes',
    )
  }

  ctx.on('agent/turn-stopping', async ({ agent, turn, signal }) => {
    scheduleAutomaticDocumentation(ctx, agent, turn, signal)
  })

  ctx.logger?.info?.('[dsh-learning-coder] automatic post-task documentation enabled')
}
